### PR TITLE
Upstream debian patches and a fix for the install-libmxml.a make target

### PR DESCRIPTION
**Pull request by g0hl1n**
This PR aims to upstream the patches from Debians mxml (https://packages.debian.org/source/buster/mxml) source archive.
Furthermore I've added the libmxml.a dependency for the install-libmxml.a make target

### CODE REVIEW

**Comment by michaelrsweet** [comment]
OK, so I know for a fact that the rpath options ARE necessary on HP-UX and macOS, so I won't accept those changes. I can separate out the Linux-specific DSO commands, however, to eliminate rpath there (although historically not including rpath when prefix is /usr/local has been problematic...)

I also can't take all of the header changes as-is, but will make sure the equivalents are incorporated.

Note: autoheader IS NOT USED FOR THIS PROJECT. I will consider taking the AC_DEFINE description strings, but I explicitly warn you NOT to use autoheader when packaging Mini-XML as it may cause problems that I cannot help you solve.

**Comment by g0hl1n** [comment]
Hello Michael, thank you for your feedback!

I'm sorry for sending those "invalid" patches, I simply haven't investigated enough on rpath and the headers regarding non-Linux platforms.

It would be great if you can merge the AC_DEFINE strings as otherwise the build fails for at least Debian and Yocto.

So should I update this PR or will you incorporate those changes within this PR yourself?

**Comment by michaelrsweet** [comment]
@g0hl1n How does the build fail for Debian and Yocto when the AC_DEFINE macros don't have the OPTIONAL description string?

I've started incorporating the makefile and configure script changes and will hopefully have the major changes merged soon.

**Comment by michaelrsweet** [comment]
OK, I've pushed the remainder of the changes I'm willing to make to master.

WRT the autoheader comments for all of the AC_DEFINE, I WILL NOT add them because:

1. autoheader completely rewrites config.h.in, removing the copyright header, extra include files, and other conditional code. This breaks the build (which is why you needed to patch the other files in an unmaintainable way.
2. While I could spend time on using the AH_TOP, AH_BOTTOM, and/or AH_TEMPLATE macros to get autoheader to generate a valid config.h.in file, Mini-XML is a trivial project to support with just autoconf and I really have no desire to further complicate the build system.
3. Other projects of mine that are packaged for Debian (in particular, CUPS, HTMLDOC, and FLTK) do not make these kinds of changes. Clearly it is not a requirement for a project to support autoheader.

In order to make things clear about me NOT supporting autoheader (just as I do NOT support automake or libtool crap), I have added an AH_TOP macro that inserts a `#error` message explaining why you cannot use autoheader with this project. (I hope you understand)

**Comment by g0hl1n** [comment]
@michaelrsweet thanks for integrating the changes and pointing out to not use autoheader for mxml.
Therefore I've changed the OpenEmbedded recipe to not using autoheader.
Now everything works as expected (at least from my point of view).

Thanks again!

**Pull request closed without merging**
