### PR TITLE
allow to override man-page date

### PR DESCRIPTION
**Pull request by bmwiedemann**
in order to allow for reproducible builds.
See https://reproducible-builds.org/ for why this is good
and https://reproducible-builds.org/specs/source-date-epoch/
for the definition of this variable.

### CODE REVIEW

**Comment by michaelrsweet** [comment]
I'd prefer not to use an environment variable for this, but am happy to add a command-line argument that can pass the environment variable.

**Comment by bmwiedemann** [comment]
The disadvantage with command-line arguments is that every distribution needs to add it explicitly in their build process, which this variable is only set in one place and already used by hundreds of packages.

**Comment by michaelrsweet** [comment]
and the disadvantage of the environment variable is that it can cause unintended behavior...  This isn't the only place I'd need to change things - also the HTML, docset, and new EPUB support...

I assume you've addressed the compiler tool chain issues already?

**Comment by bmwiedemann** [comment]
At least for mxml itself, this was the only issue. And yes, we got such patches into gcc, cmake and rpm upstream already, so we can already build 8098 of 10636 openSUSE packages with bit-identical results.
I publish such stats (updated every few weeks) at http://rb.zq1.de/compare.factory/rbstats
and diffs like http://rb.zq1.de/compare.factory-20170324/mxml-compare.out

What 'unintended behaviour' are you afraid of? Some concerns are already addressed in the source-date-epoch FAQ.

**Comment by michaelrsweet** [comment]
I've committed a simpler change to support the environment variable.

[master b79d3e0] Add support for SOURCE_DATE_EPOCH environment variable (Issue #193)

**Comment by bmwiedemann** [comment]
tested your change. works nicely. Thanks again.

**Pull request closed without merging**
